### ISSUE TITLE
Add continuous deployment

### ISSUE THREAD

**Issue by y0m0** [Charliefea/Acebook#25]
┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;Charliefea&#x2F;Acebook&#x2F;issues&#x2F;25">#25 Add continuous deployment</a>

**Comment by georn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add continuous deployment](https://trello.com/c/JjFVCXWa/21-add-continuous-deployment)
